" vim: foldmethod=marker foldlevel=2
" General Settings {{{3
set nocompatible
let mapleader="\<Space>"
set rtp+=~/.vim/bundle/Vundle.vim/
set wildignore+=*.py~,build/*.*,*.class,*.pyc,__pycache__*

" Helps when <tab> completing strings on vim's command line
set wildmenu
set wildmode=list:longest
set backupdir=/tmp,~/.vim/.backups,.
set t_Co=256
set guioptions-=T
set guioptions-=m

set backspace=indent,eol,start

set splitbelow
set backup		" keep a backup file
set history=128		" keep 50 lines of command line history
set ruler		" show the cursor position all the time
set number
set laststatus=2 "every window will show the statusline
set showcmd		" display incomplete commands
set incsearch		" do incremental searching
set hlsearch
syntax on

set ts=2
set sw=2
set et

filetype plugin indent on
set autoindent
set autoread

set swapfile
set background=dark
if has('termguicolors')
  set termguicolors
endif

set noerrorbells
set vb t_vb=

" http://input.fontbureau.com/
set guifont=Input\ Regular\ 12
" }}} General Settings "

nnoremap ; :

" Complete reference about what do you get with this vimrc {{{3
" Basic Docs about installed plugins
"
"
"
" Finding things
"
" <leader>a Searches for the word under cursor wit Ack (All files under
" current directory)
" <leader>la Does the same but only on current file
" Both work for currently selected string
"
" CTRL-F on insert mode uses Ack to find word under cursos (all files)
"
" Managing Buffers
"
" <leader>b Opens the Buffer manager window, where you can open/delete buffers
"
" How to use some plugins
"
" vim-scripts/Merginal
" Inside branch list window
" * cc Checkout selected branch
" * A Create a new branch based on currently checked out branch
" * M merge branch under cursor with current checked out branch
" * rn Prompt to renamea branch under cursor
"
" tpope/vim-fugitive
" Inside fugitive window
" cc Commit current files
" ca Commit ammend (can edit commit message)
" cA Commit ammend with current commit message
" dp Display unified diff of file
"
" }}} Complete reference about what do you get with this vimrc "

" Plugin installation {{{2

let g:ale_fix_on_save = 1
let g:ale_fixers = {
\   '*': ['remove_trailing_lines', 'trim_whitespace'],
\   'python': ['black', 'isort'],
\}
let g:ale_python_black_options = '--line-length 80'
let g:ale_python_mypy_auto_pipenv = 1
let g:ale_python_mypy_options = '--ignore-missing-imports'

let g:ale_completion_enabled = 1
let g:ale_completion_delay = 30
"
" Não sublinhar as linhas que o linter (pyls) acusar problemas
let g:ale_set_highlights = 0

let g:ale_linters = {
      \ 'python': ['mypy', 'pyls'],
\}

set completeopt=menu,menuone,preview,noselect,noinsert
imap <C-Space> <Plug>(ale_complete)


call vundle#begin()

" Dependency for idanarye/vim-vebugger
Plugin 'Shougo/vimproc.vim', {'do' : 'make'}

" Dependenxy to janko-m/vim-test
Plugin 'tpope/vim-dispatch'

" Dependencies for sirver/ultisnips
Plugin 'MarcWeber/vim-addon-mw-utils'
Plugin 'tomtom/tlib_vim'
Plugin 'honza/vim-snippets'


" Syntax plugins
Plugin 'cespare/vim-toml'
Plugin 'ekalinin/Dockerfile.vim'

" Plugins

Plugin 'sirver/ultisnips'

Plugin 'bling/vim-airline'

Plugin 'kien/ctrlp.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-unimpaired'
Plugin 'vim-scripts/surround.vim'
Plugin 'matze/vim-move'
Plugin 'myusuf3/numbers.vim'
Plugin 'alvan/vim-closetag'

Plugin 'EinfachToll/DidYouMean'
Plugin 'mhinz/vim-signify'
Plugin 'nathanaelkane/vim-indent-guides' " <leader>ig to toggle visbility
Plugin 'airblade/vim-rooter'
Plugin 'artur-shaik/vim-javacomplete2' " Run mvn complie inside .vim/bundle/vim-javacomplete2/libs/javavi
Plugin 'idanarye/vim-merginal'
Plugin 'elzr/vim-json' " checking for json files, highlighting errors
Plugin 'alfredodeza/pytest.vim'
Plugin 'mileszs/ack.vim'
Plugin 'daltonmatos/vim-virtualenv'
Plugin 'sandeepcr529/Buffet.vim'
Plugin 'ntpeters/vim-better-whitespace'
Plugin 'idanarye/vim-vebugger'
Plugin 'gregsexton/gitv'

Plugin 'w0rp/ale'

Plugin 'janko-m/vim-test'
"
" ColorSchemes
Plugin 'chriskempson/base16-vim'
Plugin 'Addisonbean/Vim-Xcode-Theme'

call vundle#end()
" }}} Plugin installation



" Thanks to @denilsonsa (https://github.com/denilsonsa)
function! Salvar_setKeys()
  "Use Ctrl+S to save
  nnoremap <silent> <C-S>      :update<CR>
  vnoremap <silent> <C-S> <C-C>:update<CR>
endfunc

augroup Salvar
  autocmd!
  autocmd GUIEnter * call Salvar_setKeys()
augroup END

colorscheme base16-dracula
" Better colors for the line numbers
highlight LineNr guifg=White

nmap <leader>w <C-W>

" Expand %% (on the command line) to the directory of current file
cnoremap %% <C-R>=expand('%:p:h').'/'<CR>

nnoremap <silent> <leader>wr :setlocal wrap!<CR>
nnoremap <silent> <leader>x  :w<CR>
nnoremap <silent> <leader>X  :x<CR>

" set CTRL-G to always show full path of current file when
nnoremap <silent> <C-G>  1<C-G>

"Ctrl+F4 closes current buffer
" nnoremap <C-F4> :close<cr>
nnoremap <leader>q :close<cr>
nnoremap <C-h> <C-W>h
nnoremap <C-l> <C-W>l
nnoremap <C-j> <C-W>j
nnoremap <C-k> <C-W>k

nnoremap <leader>b :Bufferlist<CR>
nnoremap <silent> <leader>bW :bwipe!<CR>

"Desliga highlight search
nnoremap <leader><space> :nohls <enter>

" Mapping for search using :Ack
nnoremap <leader>a :Ack <cword><CR>
inoremap <C-F> <ESC>:Ack <cword><CR>
" When on VISUAL mode:
" yank current selected text to default register (y)
" Selects Ack for search (:Ack)
" Types default register's content back (<C-R>")
" hits enter <CR>
vnoremap <leader>a y:Ack <C-R>"<CR>

nnoremap <leader>la :Ack <cword> %<CR>
vnoremap <leader>la y:Ack <C-R>" %<CR>

" Copy/Paste from/to clipboard
vmap <Leader>y "+y
nmap <Leader>p "+p
nmap <Leader>P "+P
vmap <Leader>p "+p
vmap <Leader>P "+P


" Navigate to previous tag o tagstack
nmap <leader>[ :pop<CR>

" For Syntastic
" Recomended settings
set statusline+=%#warningmsg#
set statusline+=%*

nnoremap <leader>en :lnext<CR>
nnoremap <leader>ep :lprev<CR>
nnoremap <leader>el :lopen<CR>

" Close the QuickFix/Loc Windows hitting 'q'

augroup QuickCloser
  autocmd!
  autocmd BufWinEnter quickfix nnoremap <buffer> q :cclose<CR>
  autocmd BufWinEnter quickfix nnoremap <buffer> <ESC> :cclose<CR>

  autocmd BufWinEnter terminal nnoremap <buffer> <ESC> :close<CR>
  autocmd BufWinEnter terminal nnoremap <buffer> q :close<CR>

  autocmd FileType netrw nnoremap <buffer> q :close<CR>
  autocmd FileType netrw nnoremap <buffer> <ESC> :close<CR>
augroup END

" For sirver/ultisnips
let g:UltiSnipsExpandTrigger="<C-J>"

" For closetag plugin
autocmd FileType html,htmldjango,jinjahtml,eruby,mako let b:closetag_html_style=1
let g:closetag_filenames = "*.html,*.xhtml,*.phtml,*.xml"

noremap <Leader>e :25Lexplore<CR>

" New tab
noremap <C-t> :tabnew<CR>
noremap <leader>t :tab sball<CR>

" Some interesting annotations about vim commands
" Macros:
" qa = inicia a gravação no registrador a (poderia ser qualquer letra)
" q = termina a gravação
" @a = executa a macro gravada em a
" @@ = re-executa a última macro
"
" Copy-and-paste from different registers:
" "a = Usa o registrador a (veja :help registers para lista de registradores)
" "+ = buffer de ctrl+c e ctrl+v
" "* = buffer de X11 primary selection
" "/ = buffer de busca
"
" No modo de inserção (ou na linha de :comando):
" ^R seguido de um registrador = insere o conteúdo daquele registrador
"

augroup Filetypes
  autocmd!
  autocmd BufRead,BufNewFile *.ino set filetype=cpp
  autocmd BufRead,BufNewFile Dockerfile-* set syntax=dockerfile
augroup END

nnoremap <Leader>v :tabedit $MYVIMRC<cr>
nnoremap <Leader>s :tabedit ~/.ssh/config<cr>
nnoremap <Leader>z :tabedit $ZDOTDIR/.zshrc<cr>
nnoremap <silent> <C-S-PageUP> :tabm -1<CR>
nnoremap <silent> <C-S-PageDOWN> :tabm +1<CR>

function! SourceFileIfExist(filename)
  let l:extra_file = fnamemodify(expand($MYVIMRC), ':p:h') . '/' . a:filename
  if filereadable(l:extra_file)
    execute ':so ' . l:extra_file
  endif
endfunc

call SourceFileIfExist('airline.vim')
call SourceFileIfExist('ctrlp.vim')
call SourceFileIfExist('extra.vim')
call SourceFileIfExist('java.vim')
call SourceFileIfExist('git.vim')
call SourceFileIfExist('vim-wiki.vim')
call SourceFileIfExist('lh-tags.vim')
call SourceFileIfExist('vim-do.vim')
call SourceFileIfExist('vim-test.vim')
call SourceFileIfExist('pytest.vim')
call SourceFileIfExist('terminal.vim')
call SourceFileIfExist('python.vim')
call SourceFileIfExist('vim-rooter.vim')
call SourceFileIfExist('signify.vim')
