" vim: foldmethod=marker foldlevel=2
" General Settings {{{3
set nocompatible
let mapleader="\<Space>"
set rtp+=~/.vim/bundle/Vundle.vim/
set wildignore+=*.py~,build/*.*,*.class,*.pyc,__pycache__*

" Helps when <tab> completing strings on vim's command line
set wildmenu
set wildmode=list:longest
set backupdir=/tmp,~/.vim/.backups,.
set t_Co=256
set guioptions-=T
set guioptions-=m

set backspace=indent,eol,start

set splitbelow
set backup		" keep a backup file
set history=128		" keep 50 lines of command line history
set ruler		" show the cursor position all the time
set number
set laststatus=2 "every window will show the statusline
set showcmd		" display incomplete commands
set incsearch		" do incremental searching
set hlsearch
syntax on

set ts=2
set sw=2
set et

filetype plugin indent on
set autoindent
set autoread

set swapfile
set background=dark
if has('termguicolors')
  set termguicolors
endif

set noerrorbells
set vb t_vb=

" http://input.fontbureau.com/
set guifont=Input\ Regular\ 12
" }}} General Settings "

nnoremap ; :

" Complete reference about what do you get with this vimrc {{{3
" Basic Docs about installed plugins
"
"
"
" Finding things
"
" <leader>a Searches for the word under cursor wit Ack (All files under
" current directory)
" <leader>la Does the same but only on current file
" Both work for currently selected string
"
" CTRL-F on insert mode uses Ack to find word under cursos (all files)
"
" Managing Buffers
"
" <leader>b Opens the Buffer manager window, where you can open/delete buffers
"
" How to use some plugins
"
" vim-scripts/Merginal
" Inside branch list window
" * cc Checkout selected branch
" * A Create a new branch based on currently checked out branch
" * M merge branch under cursor with current checked out branch
" * rn Prompt to renamea branch under cursor
"
" tpope/vim-fugitive
" Inside fugitive window
" cc Commit current files
" ca Commit ammend (can edit commit message)
" cA Commit ammend with current commit message
" dp Display unified diff of file
"
" }}} Complete reference about what do you get with this vimrc "

" Plugin installation {{{2

let g:ale_fix_on_save = 1
let g:ale_fixers = {
\   '*': ['remove_trailing_lines', 'trim_whitespace'],
\   'python': ['black'],
\}
let g:ale_python_black_options = '--line-length 80'


call vundle#begin()

" Dependency for idanarye/vim-vebugger
Plugin 'Shougo/vimproc.vim', {'do' : 'make'}

" Dependenxy to janko-m/vim-test
Plugin 'tpope/vim-dispatch'

" Dependencies for sirver/ultisnips
Plugin 'MarcWeber/vim-addon-mw-utils'
Plugin 'tomtom/tlib_vim'
Plugin 'honza/vim-snippets'


" Syntax plugins
Plugin 'cespare/vim-toml'
Plugin 'ekalinin/Dockerfile.vim'

" Plugins

Plugin 'sirver/ultisnips'

Plugin 'bling/vim-airline'

Plugin 'kien/ctrlp.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-unimpaired'
Plugin 'vim-scripts/surround.vim'
Plugin 'davidhalter/jedi-vim'
Plugin 'Shougo/neocomplete.vim'
Plugin 'ervandew/supertab'
Plugin 'matze/vim-move'
Plugin 'myusuf3/numbers.vim'
Plugin 'alvan/vim-closetag'

Plugin 'EinfachToll/DidYouMean'
Plugin 'mhinz/vim-signify'
Plugin 'nathanaelkane/vim-indent-guides' " <leader>ig to toggle visbility
Plugin 'airblade/vim-rooter'
Plugin 'artur-shaik/vim-javacomplete2' " Run mvn complie inside .vim/bundle/vim-javacomplete2/libs/javavi
Plugin 'idanarye/vim-merginal'
Plugin 'elzr/vim-json' " checking for json files, highlighting errors
Plugin 'vim-syntastic/syntastic'
Plugin 'alfredodeza/pytest.vim'
Plugin 'mileszs/ack.vim'
Plugin 'daltonmatos/vim-virtualenv'
Plugin 'sandeepcr529/Buffet.vim'
Plugin 'ntpeters/vim-better-whitespace'
Plugin 'idanarye/vim-vebugger'
Plugin 'gregsexton/gitv'

Plugin 'w0rp/ale'

Plugin 'janko-m/vim-test'
"
" ColorSchemes
Plugin 'chriskempson/base16-vim'
Plugin 'Addisonbean/Vim-Xcode-Theme'

call vundle#end()
" }}} Plugin installation



" Thanks to @denilsonsa (https://github.com/denilsonsa)
function! Salvar_setKeys()
  "Use Ctrl+S to save
  nnoremap <silent> <C-S>      :update<CR>
  vnoremap <silent> <C-S> <C-C>:update<CR>
endfunc

augroup Salvar
  autocmd!
  autocmd GUIEnter * call Salvar_setKeys()
augroup END

colorscheme base16-dracula
" Better colors for the line numbers
highlight LineNr guifg=White

nmap <leader>w <C-W>

" Expand %% (on the command line) to the directory of current file
cnoremap %% <C-R>=expand('%:p:h').'/'<CR>

nnoremap <silent> <leader>wr :setlocal wrap!<CR>
nnoremap <silent> <leader>x  :w<CR>
nnoremap <silent> <leader>X  :x<CR>

" set CTRL-G to always show full path of current file when
nnoremap <silent> <C-G>  1<C-G>

"Ctrl+F4 closes current buffer
" nnoremap <C-F4> :close<cr>
nnoremap <leader>q :close<cr>
nnoremap <C-h> <C-W>h
nnoremap <C-l> <C-W>l
nnoremap <C-j> <C-W>j
nnoremap <C-k> <C-W>k

nnoremap <leader>b :Bufferlist<CR>
nnoremap <silent> <leader>bW :bwipe!<CR>

"Desliga highlight search
nnoremap <leader><space> :nohls <enter>

" Mapping for search using :Ack
nnoremap <leader>a :Ack <cword><CR>
inoremap <C-F> <ESC>:Ack <cword><CR>
" When on VISUAL mode:
" yank current selected text to default register (y)
" Selects Ack for search (:Ack)
" Types default register's content back (<C-R>")
" hits enter <CR>
vnoremap <leader>a y:Ack <C-R>"<CR>

nnoremap <leader>la :Ack <cword> %<CR>
vnoremap <leader>la y:Ack <C-R>" %<CR>

" Copy/Paste from/to clipboard
vmap <Leader>y "+y
nmap <Leader>p "+p
nmap <Leader>P "+P
vmap <Leader>p "+p
vmap <Leader>P "+P


" Navigate to previous tag o tagstack
nmap <leader>[ :pop<CR>

" For Syntastic
" Recomended settings
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_python_checkers = ['python']
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 0
let g:syntastic_stl_format = '[%E{Err: %fe #%e}%B{, }%W{Warn: %fw #%w}]'

nnoremap <leader>en :lnext<CR>
nnoremap <leader>ep :lprev<CR>
nnoremap <leader>el :lopen<CR>

" Close the QuickFix/Loc Windows hitting 'q'

augroup QuickCloser
  autocmd!
  autocmd BufWinEnter quickfix nnoremap <buffer> q :cclose<CR>
  autocmd BufWinEnter quickfix nnoremap <buffer> <ESC> :cclose<CR>

  autocmd BufWinEnter terminal nnoremap <buffer> <ESC> :close<CR>
  autocmd BufWinEnter terminal nnoremap <buffer> q :close<CR>

  autocmd FileType netrw nnoremap <buffer> q :close<CR>
  autocmd FileType netrw nnoremap <buffer> <ESC> :close<CR>
augroup END

" For sirver/ultisnips
let g:UltiSnipsExpandTrigger="<C-J>"

" For airblade/vim-rooter
let g:rooter_change_directory_for_non_project_files = 'home'
let g:rooter_silent_chdir = 1
let g:rooter_resolve_links = 1

" For signify plugin
let g:signify_vcs_list = ['git']
let g:signify_realtime = 1
let g:signify_cursorhold_normal = 0
let g:signify_cursorhold_insert = 0

" For closetag plugin
autocmd FileType html,htmldjango,jinjahtml,eruby,mako let b:closetag_html_style=1
let g:closetag_filenames = "*.html,*.xhtml,*.phtml,*.xml"

" Supertab
let g:SuperTabContextDefaultCompletionType = "<c-n>"
let g:SuperTabDefaultCompletionType = "<c-n>"


noremap <Leader>e :25Lexplore<CR>


""" Vim-AirLine
"
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#show_splits = 0 " Remove o nome do buffer no canto direito da tabline
let g:airline#extensions#tabline#buf_label_first = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#show_buffers = 0
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#tab_nr_type = 2 " splits and tab number
let g:airline#extensions#tabline#fnamemod = ':p:.'
let g:airline#extensions#tabline#formatter = 'unique_tail_improved'
let g:airline#extensions#tabline#show_close_button = 0
let g:airline#extensions#virtualenv#enabled = 1
let g:airline#extensions#hunks#enabled = 0 " We have signify enabled
let g:virtualenv_stl_format = 'ጸ (%{get(g:, "virtualenv_name")})'
let g:airline#extensions#tagbar#enabled = 0
let g:airline_left_sep = ""
let g:airline_right_sep = ""
let g:airline_section_c = airline#section#create(['Project: %{getcwd()}'])
let g:airline_mode_map = {
      \ '__' : '-',
      \ 'n'  : 'N',
      \ 'i'  : 'I',
      \ 'R'  : 'R',
      \ 'c'  : 'C',
      \ 'v'  : 'V',
      \ 'V'  : 'V',
      \ '' : 'V',
      \ 's'  : 'S',
      \ 'S'  : 'S',
      \ '' : 'S',
      \ 't' : 'T',
      \ }
let g:airline_right_alt_sep = ''

let g:airline_section_x = '%{airline#util#prepend("",0)}%{airline#util#wrap(python#empty_ft(),0)}'

" New tab
noremap <C-t> :tabnew<CR>
noremap <leader>t :tab sball<CR>

""" CTRLP
"
let g:ctrlp_cmd = "CtrlP"
let g:ctrlp_working_path_mode = 'ra'
let g:ctrlp_regexp = 1
let g:ctrlp_switch_buffer = 'Et'
let g:ctrlp_match_window = 'max:20'
let g:ctrlp_use_caching = 1
let g:ctrlp_cache_dir = $HOME.'/.cache/ctrlp'
let g:ctrlp_max_depth = 10

let g:ctrlp_prompt_mappings = {
    \ 'AcceptSelection("e")': ['<c-t>'],
    \ 'AcceptSelection("t")': ['<cr>', '<2-LeftMouse>'],
    \ }

let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/](dist|node_modules)$',
  \ }
nnoremap <C-D> :CtrlP ~/

" Some interesting annotations about vim commands
" Macros:
" qa = inicia a gravação no registrador a (poderia ser qualquer letra)
" q = termina a gravação
" @a = executa a macro gravada em a
" @@ = re-executa a última macro
"
" Copy-and-paste from different registers:
" "a = Usa o registrador a (veja :help registers para lista de registradores)
" "+ = buffer de ctrl+c e ctrl+v
" "* = buffer de X11 primary selection
" "/ = buffer de busca
"
" No modo de inserção (ou na linha de :comando):
" ^R seguido de um registrador = insere o conteúdo daquele registrador
"

augroup Filetypes
  autocmd!
  autocmd BufRead,BufNewFile *.ino set filetype=cpp
  autocmd BufRead,BufNewFile Dockerfile-* set syntax=dockerfile
augroup END

nnoremap <Leader>v :tabedit $MYVIMRC<cr>
nnoremap <Leader>s :tabedit ~/.ssh/config<cr>
nnoremap <Leader>z :tabedit $ZDOTDIR/.zshrc<cr>
nnoremap <silent> <C-S-PageUP> :tabm -1<CR>
nnoremap <silent> <C-S-PageDOWN> :tabm +1<CR>

function! SourceFileIfExist(filename)
  let l:extra_file = fnamemodify(expand($MYVIMRC), ':p:h') . '/' . a:filename
  if filereadable(l:extra_file)
    execute ':so ' . l:extra_file
  endif
endfunc

call SourceFileIfExist('extra.vim')
call SourceFileIfExist('java.vim')
call SourceFileIfExist('git.vim')
call SourceFileIfExist('vim-wiki.vim')
call SourceFileIfExist('lh-tags.vim')
call SourceFileIfExist('vim-do.vim')
call SourceFileIfExist('vim-test.vim')
call SourceFileIfExist('pytest.vim')
call SourceFileIfExist('terminal.vim')
call SourceFileIfExist('python.vim')

function! StripWhitespaceOnSave()
  " If we have ntpeters/vim-better-whitespace lodaed, strip whitespaces when
  " saving
  if exists(':StripWhitespace') == 2 "Full match of command name
    augroup Whitespace
      autocmd!
      autocmd BufWrite java,python,text StripWhitespace
      autocmd FileType buffet :ToggleWhitespace
    augroup END
  endif
endfunction

autocmd VimEnter * call StripWhitespaceOnSave()


