#Icons
# Home:  (\uF015)
# Right Sep:  (\ue0c6)
# Left Sep:  (\ue0c7)
# Github:  (\uf09b)
# Time:  (\uf017)
#  (\uf303)
# 󰌑
#  (\u3727)
#  (\ue73c)
# 笠 (\uf9f8)
#  (\uf407) Indicação se a branch atua tem um PR aberto. Mostrar o número do PR
#  gh pr list --json baseRefName,number,headRefName --head $(git rev-parse --abbrev-ref HEAD) --jq '.[] | .number' | cat
# Clickable text: https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda

format="""
$os\
$directory\
$git_branch\
$git_commit\
${custom.github_pr}\
$git_metrics\
$git_state\
$all\
$character
"""
right_format="${jobs}$cmd_duration$status"
add_newline = false

[character]
disabled = false

[directory]
home_symbol="~"
style="bg:blue bold fg:white"
read_only_style="bg:blue bold fg:white"
format = "[ $path ]($style)[$read_only]($read_only_style)[ ](bg:none fg:blue)"

[directory.substitutions]
"/home/daltonmatos/" = "SRC?"

[jobs]
symbol = "&:"
symbol_threshold = 1
number_threshold = 1

[fill]
disabled = true

[cmd_duration]
format="[ $duration]($style) "

[status]
disabled = false
symbol="󰌑"
format="[$status$symbol]($style)"

[nodejs]
disabled = false

[os]
format = "[ $symbol  ]($style)[](bg:blue)"
disabled = false
style = "bg:white fg:black"

[os.symbols]
#Ubuntu = ""
Ubuntu = ""
#Ubuntu = ""

[python]
disabled = false
pyenv_version_name = false
pyenv_prefix = "pyenv "
python_binary = [
    "python",
    "python3",
    "python2",
]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
version_format = "v${raw}"
style = "yellow"
symbol = " "
detect_extensions = ["py"]
detect_files = [
    "requirements.txt",
    ".python-version",
    "pyproject.toml",
    "Pipfile",
    "tox.ini",
    "setup.py",
    "__init__.py",
]
detect_folders = []

[gcloud]
disabled = true

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
symbol = " "
style = "fg:bold cyan bg:none"

[git_commit]
only_detached = false
tag_disabled = false
format = '[($hash$tag )]($style)'
style = "green"
#tag_symbol = " 笠"

[git_state]
disabled = false

[git_metrics]
disabled = false

[terraform]
format = "[$symbol$version \\($workspace\\)]($style) "

[custom.github_pr]
format = "[($symbol $output )]($style)"
require_repo = true
command ="""
gh pr list --json baseRefName,number,headRefName --head $(git rev-parse --abbrev-ref HEAD) --jq '.[] | .number' | cat
"""
when = "true"
symbol = ""
style = "blue"
ignore_timeout = true
disabled = true

[custom.python]
format = "[($output )]($style)"
command ="""
python -c 'print("#42")'
"""
when = "true"
style = "blue"
disabled = true
