export ZDOTDIR=${HOME}/.zsh

export LC_CTYPE=pt_BR.UTF-8
export TERM="xterm-256color"
export TERMINAL="xfce4-terminal"
export EDITOR=vim

export ANTIDOTE_CLONE_DIR=${HOME}/.antidote
export ANTIDOTE_HOME=${ANTIDOTE_CLONE_DIR}/.plugins
export STARSHIP_CONFIG=${HOME}/.config/starship.toml

export MAGIC_ENTER_GIT_COMMAND="git status "
