
source $ZDOTDIR/zstyles
source ${ZDOTDIR}/antidote.zsh

#GPG specifics
GPG_TTY=$(tty)
export GPG_TTY

[[ -a ~/.shell-extras.sh ]] && . ~/.shell-extras.sh

decrypt_env() {
  local env_name_sufix=$1
  local env_name=CRYPT_${env_name_sufix}
  gpg -d <<<${(P)env_name} 2>/dev/null
}
