# /etc/skel/.bashrc
#
# This file is sourced by all *interactive* bash shells on startup,
# including some apparently interactive shells such as scp and rcp
# that can't tolerate any output.  So make sure this doesn't display
# anything or bad things will happen !


# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
	# Shell is non-interactive.  Be done now!
	return
fi


alias esync='sudo eix-sync '
alias eworld='sudo emerge -auDNv world'
alias esys='sudo emerge -auDNv system'
alias einst='sudo emerge'
alias eumask='sudo autounmask'
alias euinst='sudo emerge -C'
alias revdep='sudo revdep-rebuild'
alias flag='sudo flaggie'
alias etcupdate='sudo etc-update'
alias eq='equery '
alias py='ipython'
alias dfh='df -hP | sed -e "s/Sist. Arq./Sist.Arq./" | column -t'
alias gf='git flow'
alias wscan='sudo iwlist eth1 scan'
alias enews='eselect news'
alias ebelong='eq b'
alias edepend='eq d'
alias efiles='eq f'

# Tmux aliases
alias tl='tmux ls'
alias ta='tmux attach -t'

alias gvimrtab='gvim --remote-tab-silent '
export LANG="pt_BR.utf8"
export LC_ALL="pt_BR.utf8"
HISTCONTROL="ignoreboth"
EDITOR=vim

git_branch(){
python <<PYTHON
import sys
import subprocess
from subprocess import PIPE

s = subprocess.Popen(["git","branch"], stdout=PIPE, stderr=PIPE)
o, e = s.communicate()
for branch in o.split('\n'):
  if branch and branch[0] == '*':
    print ",{0}".format(branch[2:])
PYTHON

}

PS1='\[\033[01;32m\]\u@\h\[\033[01;34m\] \w [\#$(git_branch)]\$\[\033[00m\] '

export LANGUAGE=pt_BR

alias hoff='HISTFILE=/dev/null bash'

PATH=$PATH:~/src/less.js/bin/

export TERM="xterm-256color"

#For virtualenvwrapper
export VIRTUALENVWRAPPER_VIRTUALENV_ARGS='--no-site-packages'

[[ -f /usr/bin/virtualenvwrapper.sh ]] && source /usr/bin/virtualenvwrapper.sh

# Debian-likes
[[ -f /usr/local/bin/virtualenvwrapper.sh ]] && source /usr/local/bin/virtualenvwrapper.sh

